H3K27ac.immunoseq.RData: immunoseq.calls.R
	R --no-save < $<
immunoseq.calls.RData: immunoseq.calls.R
	R --no-save < $<
figure-gctest-coverage.png: figure-gctest-coverage.R gctest.RData
	R --no-save < $<
gctest.RData: gctest.R
	R --no-save < $<
public.private.immunoseq.csv: public.private.immunoseq.R
	R --no-save < $<
